improve output and also check /etc/hosts

diff --git a/config.sys/lint-hostname b/config.sys/lint-hostname
--- a/config.sys/lint-hostname
+++ b/config.sys/lint-hostname
@@ -5,19 +5,14 @@ HF=$(hostname -f)
 EH=$(cat /etc/hostname)
 DOMAIN=$(dnsdomainname)
 
-echo "hostname -s   $HS"
-echo "hostname -f   $HF"
-echo "/etc/hostname $EH"
-echo "dnsdomainname $DOMAIN"
-echo "IP            $IP"
-echo "DNS           $FQDN"
-
-if [ ! $HS = $EH ]; then
-    echo hostname -s does not match /etc/hostname
-fi
-if [ ! $HF = $EH.$DOMAIN ]; then
-    echo hostname -f does not match hostname -s with dnsdomainname attached
-fi
-if [ ! $FQDN = $HF ]; then
-    echo DNS entry does not match hostname -f
-fi
+echo "hostname -s     $HS"
+echo "hostname -f     $HF"
+echo "/etc/hostname   $EH"
+echo "dnsdomainname   $DOMAIN"
+echo "IP              $IP"
+echo "DNS             $FQDN"
+echo
+if [ ! $HS = $EH ]; then echo hostname -s does not match /etc/hostname; fi
+if [ ! $HF = $EH.$DOMAIN ]; then echo hostname -f does not match hostname -s with dnsdomainname attached; fi
+if [ ! $FQDN = $HF ]; then echo DNS entry does not match hostname -f; fi
+grep "$IP.*$FQDN.*$HS" /etc/hosts >/dev/null || echo "$IP\t$FQDN\t$HS entry not found in /etc/hosts"
